[package]
name = "just_x11"
version = "0.1.0"
edition = "2021"
authors = ["Tomasz Maciosowski <t4ccer@gmail.com>"]
license = "AGPL-3.0"
readme = "README.md"

[dependencies]
just_shared_memory = {path = "../just_shared_memory"}