[package]
name = "justshow"
version = "0.0.1"
edition = "2021"
authors = ["Tomasz Maciosowski <t4ccer@gmail.com>"]
license = "AGPL-3.0"
readme = "README.md"
repository = "https://github.com/t4ccer/justshow"
description = ""

[[bin]]
name = "pong"

[[bin]]
name = "xlsfonts"