[package]
name = "just_immui"
version = "0.1.0"
edition = "2021"

[dependencies]
just_x11 = {path = "../just_x11"}
just_x11_simple = {path = "../just_x11_simple"}
just_shared_memory = {path = "../just_shared_memory"}
just_bdf = {path="../just_bdf"}
