use crate::utils::impl_resource_id;

impl_resource_id!(AtomId);

pub mod predefined {
    use crate::{atoms::AtomId, ResourceId};

    const PRIMARY: AtomId = AtomId(ResourceId { value: 1 });
    const SECONDARY: AtomId = AtomId(ResourceId { value: 2 });
    const ARC: AtomId = AtomId(ResourceId { value: 3 });
    const ATOM: AtomId = AtomId(ResourceId { value: 4 });
    const BITMAP: AtomId = AtomId(ResourceId { value: 5 });
    const CARDINAL: AtomId = AtomId(ResourceId { value: 6 });
    const COLORMAP: AtomId = AtomId(ResourceId { value: 7 });
    const CURSOR: AtomId = AtomId(ResourceId { value: 8 });
    const CUT_BUFFER0: AtomId = AtomId(ResourceId { value: 9 });
    const CUT_BUFFER1: AtomId = AtomId(ResourceId { value: 10 });
    const CUT_BUFFER2: AtomId = AtomId(ResourceId { value: 11 });
    const CUT_BUFFER3: AtomId = AtomId(ResourceId { value: 12 });
    const CUT_BUFFER4: AtomId = AtomId(ResourceId { value: 13 });
    const CUT_BUFFER5: AtomId = AtomId(ResourceId { value: 14 });
    const CUT_BUFFER6: AtomId = AtomId(ResourceId { value: 15 });
    const CUT_BUFFER7: AtomId = AtomId(ResourceId { value: 16 });
    const DRAWABLE: AtomId = AtomId(ResourceId { value: 17 });
    const FONT: AtomId = AtomId(ResourceId { value: 18 });
    const INTEGER: AtomId = AtomId(ResourceId { value: 19 });
    const PIXMAP: AtomId = AtomId(ResourceId { value: 20 });
    const POINT: AtomId = AtomId(ResourceId { value: 21 });
    const RECTANGLE: AtomId = AtomId(ResourceId { value: 22 });
    const RESOURCE_MANAGER: AtomId = AtomId(ResourceId { value: 23 });
    const RGB_COLOR_MAP: AtomId = AtomId(ResourceId { value: 24 });
    const RGB_BEST_MAP: AtomId = AtomId(ResourceId { value: 25 });
    const RGB_BLUE_MAP: AtomId = AtomId(ResourceId { value: 26 });
    const RGB_DEFAULT_MAP: AtomId = AtomId(ResourceId { value: 27 });
    const RGB_GRAY_MAP: AtomId = AtomId(ResourceId { value: 28 });
    const RGB_GREEN_MAP: AtomId = AtomId(ResourceId { value: 29 });
    const RGB_RED_MAP: AtomId = AtomId(ResourceId { value: 30 });
    const STRING: AtomId = AtomId(ResourceId { value: 31 });
    const VISUALID: AtomId = AtomId(ResourceId { value: 32 });
    const WINDOW: AtomId = AtomId(ResourceId { value: 33 });
    const WM_COMMAND: AtomId = AtomId(ResourceId { value: 34 });
    const WM_HINTS: AtomId = AtomId(ResourceId { value: 35 });
    const WM_CLIENT_MACHINE: AtomId = AtomId(ResourceId { value: 36 });
    const WM_ICON_NAME: AtomId = AtomId(ResourceId { value: 37 });
    const WM_ICON_SIZE: AtomId = AtomId(ResourceId { value: 38 });
    const WM_NAME: AtomId = AtomId(ResourceId { value: 39 });
    const WM_NORMAL_HINTS: AtomId = AtomId(ResourceId { value: 40 });
    const WM_SIZE_HINTS: AtomId = AtomId(ResourceId { value: 41 });
    const WM_ZOOM_HINTS: AtomId = AtomId(ResourceId { value: 42 });
    const MIN_SPACE: AtomId = AtomId(ResourceId { value: 43 });
    const NORM_SPACE: AtomId = AtomId(ResourceId { value: 44 });
    const MAX_SPACE: AtomId = AtomId(ResourceId { value: 45 });
    const END_SPACE: AtomId = AtomId(ResourceId { value: 46 });
    const SUPERSCRIPT_X: AtomId = AtomId(ResourceId { value: 47 });
    const SUPERSCRIPT_Y: AtomId = AtomId(ResourceId { value: 48 });
    const SUBSCRIPT_X: AtomId = AtomId(ResourceId { value: 49 });
    const SUBSCRIPT_Y: AtomId = AtomId(ResourceId { value: 50 });
    const UNDERLINE_POSITION: AtomId = AtomId(ResourceId { value: 51 });
    const UNDERLINE_THICKNESS: AtomId = AtomId(ResourceId { value: 52 });
    const STRIKEOUT_ASCENT: AtomId = AtomId(ResourceId { value: 53 });
    const STRIKEOUT_DESCENT: AtomId = AtomId(ResourceId { value: 54 });
    const ITALIC_ANGLE: AtomId = AtomId(ResourceId { value: 55 });
    const X_HEIGHT: AtomId = AtomId(ResourceId { value: 56 });
    const QUAD_WIDTH: AtomId = AtomId(ResourceId { value: 57 });
    const WEIGHT: AtomId = AtomId(ResourceId { value: 58 });
    const POINT_SIZE: AtomId = AtomId(ResourceId { value: 59 });
    const RESOLUTION: AtomId = AtomId(ResourceId { value: 60 });
    const COPYRIGHT: AtomId = AtomId(ResourceId { value: 61 });
    const NOTICE: AtomId = AtomId(ResourceId { value: 62 });
    const FONT_NAME: AtomId = AtomId(ResourceId { value: 63 });
    const FAMILY_NAME: AtomId = AtomId(ResourceId { value: 64 });
    const FULL_NAME: AtomId = AtomId(ResourceId { value: 65 });
    const CAP_HEIGHT: AtomId = AtomId(ResourceId { value: 66 });
    const WM_CLASS: AtomId = AtomId(ResourceId { value: 67 });
    const WM_TRANSIENT_FOR: AtomId = AtomId(ResourceId { value: 68 });
}
