[package]
name = "just_windows"
version = "0.1.0"
edition = "2021"
authors = ["Tomasz Maciosowski <t4ccer@gmail.com>"]
license = "AGPL-3.0"
readme = "README.md"

[dependencies]
just_x11 = {path = "../just_x11"}
just_x11_simple = {path = "../just_x11_simple"}
